eCommerce/Models/UserManagementViewModel.cs
namespace eCommerce.Models
{
    public class UserManagementViewModel
    {
        public List<User> Users { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool IsAdmin { get; set; }
    }
}

eCommerce/Controllers/UserManagementController.cs
using eCommerce.Models;
using eCommerce.Services;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace eCommerce.Controllers
{
    [Authorize(Roles = "admin")]
    public class UserManagementController : Controller
    {
        private readonly UserService _userService;
        private readonly ItemService _itemService;

        public UserManagementController(UserService userService, ItemService itemService)
        {
            _userService = userService;
            _itemService = itemService;
        }

        [HttpGet]
        public async Task<IActionResult> Index(UserManagementViewModel viewModel)
        {
            viewModel.Users = await _userService.GetAll();
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAccount(UserManagementViewModel viewModel)
        {
            await _userService.Create(viewModel.Username, viewModel.Password, viewModel.IsAdmin);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> DeleteAccount(string username)
        {
            var user = await _userService.GetByUsername(username);
            if (user.UserRatings != null && user.UserRatings.Count > 0)
            {
                foreach (var rating in user.UserRatings)
                {
                    var item = await _itemService.GetById(rating.ItemId);
                    item.ItemRatings.RemoveAll(x => x.UserId == user.Id);
                    _itemService.UpdateRatings(item);
                }
            }
            if (user.UserReviews != null && user.UserReviews.Count > 0)
            {
                foreach (var review in user.UserReviews)
                {
                    var item = await _itemService.GetById(review.ItemId);
                    item.ItemReviews.RemoveAll(x => x.UserId == user.Id);
                    _itemService.UpdateReviews(item);
                }
            }
            _userService.DeleteByUsername(username);
            if (username == User.Identity.Name)
            {
                await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Index");
        }
    }
}

eCommerce/Views/UserManagement/Index.cshtml
@model UserManagementViewModel

<h2>Adding account section</h2>
<div>
    <form method="post">
        <div class="form-group">
            <label asp-for="Username"></label>
            <input asp-for="Username" />
        </div>
        <div class="form-group">
            <label asp-for="Password"></label>
            <input asp-for="Password" />
        </div>
        <div class="form-group">
            <label asp-for="IsAdmin"></label>
            <input asp-for="IsAdmin" type="checkbox"/>
        </div>
        <button type="submit" class="btn btn-primary" asp-action="CreateAccount">Create</button>
    </form>
</div>
<br />
<h2>Deleting users section</h2>
<table>
    <tr>
        <td>Username</td>
        <td>Password</td>
        <td>IsAdmin</td>
        <td>Delete?</td>
    </tr>
    @foreach (var user in Model.Users)
    {
        <tr>
            <td>@user.Username</td>
            <td>@user.Password</td>
            <td><input type="checkbox" checked=@user.IsAdmin disabled /></td>
            <td><a href="@Url.Action("DeleteAccount", "UserManagement", new {username = user.Username})">Delete</a></td>
        </tr>
    }
</table>